name: Maven Build with SonarCloud
description: Composite GitHub Action that verifies a Maven Build and analyzes the results in SonarCloud

inputs:
  body:
    description: Body text for the release.
    required: false
  github-token:
    description: GITHUB_TOKEN secret
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v6
    - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      with:
        body: ${{ inputs.body }}
        token: ${{ inputs.github-token }}
